version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pipeline
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline
    ports:
    - "5432"
    volumes:
    - ./postgresql:/var/lib/postgresql
  api:
    build:
      context: .
    volumes:
    - ~/.m2:/root/.m2
    depends_on:
    - db
    environment:
    - DATABASE_URL=postgres://pipeline:pipeline@db:5432/pipeline
  frontend:
    build:
      context: ./pipeline-react
      args:
        UID: ${UID:-1002}
    volumes:
    - ./pipeline-react:/usr/src/app
    user: frontend
  web:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 3000:80
    depends_on:
      - frontend
      - api
    expose:
    - 3000
